name: google_places_models
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  equatable: ^2.0.5
  json_annotation: ^4.7.0
  
dev_dependencies:
  build_runner: ^2.3.2
  json_serializable: ^6.5.4
  very_good_analysis: ^3.1.0
