name: geolocator_client

concurrency:
  group: $-$
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main
    paths:
      - "packages/geolocator_client/**"
      - ".github/workflows/geolocator_client.yaml"

jobs:
  semantic_pull_request:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/semantic_pull_request.yml@v1

  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_channel: stable
      flutter_version: 3.7.0
