name: google_places_repo
description: Repository implementation to interact with the Google Places API via the GooglePlacesClient.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  google_places_client:
    path: ../google_places_client
  google_places_models:
    path: ../google_places_models

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0
